server:
  port: 8888
spring:
  redis:
    host: 192.168.100.128 # Redis 服务器地址
    port: 6379 # Redis 端口号
    password: 123321 # Redis 密码，如果没有则不需要配置
    database: 0 # Redis 数据库编号
  mail:
    host: smtp.qq.com
    protocol: smtp
    default-encoding: UTF-8
    username: 1614458081@qq.com
    password: ugbzsyleosvxbcbi
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    port: 587
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yhzx?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123wjz123

# 阿里云配置
oss:
  endpoint: https://oss-cn-beijing.aliyuncs.com
  keyid: LTAI5t67c9JZxxp7paHYc7qN
  keysecret: M4GK0op7TnLfEyVPtGvSLif4UVABnH
  bucketname: java-ai-learning
user:
  jwt:
    ttl: 7200000
    secret-key: wjz
    token-name: token



